### ISSUE TITLE
Consider Stash List ?

### ISSUE THREAD

**Issue by Codelica** [MRCollective/TortoiseGitToolbar#1]
Thanks for the toolbar!  Very helpful.  Just hoping you might consider adding the "Stash List" command for those of us who get buried at times. :)  Thanks...

**Comment by mbinic** [comment]
Hi Matt,

I was just about to post on this, since I did a [mirror extension for Visual Studio Code](https://github.com/mbinic/vscode-tgit) this weekend and was wondering how to get to that dialog :)

My investigation revealed the command is `TortoiseGitProc.exe" /command:reflog /ref:"refs/stash"`, so shouldn't be hard to integrate. I'd love to contribute the feature, right after I polish the VSCode extension, it's just hard to find the time...

Cheers,
___
PS: Thank you very much for this extension, it makes a huge difference and I use it every day for at least 8 hours! :)

**Comment by MattDavies** [comment]
Hey @mbinic - great to know that's the command!

Really appreciate the feedback. Can't wait until your extension is done - I definitely miss the shortcuts when I'm using Visual Studio Code!

**Comment by mbinic** [comment]
Just submitted a pull request (#12) for this, please take a look when you have a minute :)

**Comment by mbinic** [comment]
I propose to close this, since the functionality has been in for some time now :)
